apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-config
  namespace: argocd
  # namespace: ducky
spec:
  project: default
  source:
    repoURL: git@github.com:ZFlucKZ/nonprod-k8s-config.git
    targetRevision: main
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      enabled: false
      prune: true
      allowEmpty: true
      selfHeal: true