apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # add an additional local user with apiKey and login capabilities
  #   apiKey - allows generating API keys
  #   login - allows to login using UI

  # Infra
  accounts.infrakai: apiKey, login
  # disables user. User is enabled by default
  accounts.infrachicken.enabled: "true"

# Team A
  accounts.nongbird: apiKey, login
  accounts.nongbird.enabled: "true"

# Team B
  accounts.nongant: apiKey, login
  accounts.nongant.enabled: "true"